# .github/workflows/docker-build-push.yml
name: Docker Build and Push

on:
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Docker Build
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/remix-weather-app:${{ github.sha }} .
      - name: Docker Push
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/remix-weather-app:${{ github.sha }}